AWSTemplateFormatVersion: 2010-09-09
Resources:
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: test-admin
      ImageId: #ami-idを入力
      InstanceType: t2.micro
      Monitoring: false
      SecurityGroupIds:
        - !ImportValue testCF-SG
      SubnetId: !ImportValue testCF-subnet
      Tags:
        - Key: Name
          Value: test-EC2
